### ISSUE TITLE
[Question] Many projects

### ISSUE THREAD

**Issue by digitalit** [laraedit/laraedit-docker#22]
Hi,

Great docker project you got here.

I use Vagrant with Homestead on and i ad new domains/hosts/projects in the .yaml file and then just provision Vagrant.

How can i achieve this in your project?

Do i have to run an separate container for each Laravel project?

Thank you
/Peter

**Comment by lube8uy** [comment]
On my case, I mapped my projects folder into docker and then I created a virtual host for each one. To create the virtual host copy the one in /etc/nginx/sites-available/homestead and change the server_name and root lines.

**Comment by ibourgeois** [comment]
Yes, my intent was to use separate containers per project. 

If you'd like, I can create a separate branch to house a more all-in-one type of environment, but isn't that what Homestead is for?

**Comment by lube8uy** [comment]
I'm new to docker, is it possible to load many instances of the same container at the same time with each instance pointing to a different project folder? (I can't test right now, sorry)
Also, as I see in another thread, is the recommended approach to load all the databases in an instance dedicated only to mysql and point to that instance from the web projects?

Thanks for the help!

**Comment by ibourgeois** [comment]
yes, you can run multiple instances of this container at the same time with each being pointed to their own project directories.

yes, the "recommended" approach would be to run a single service (web, database, etc) in it's own container. this is because when you use docker, it is meant to allow you to ship/deploy the container from development to production without friction by deploying the actual container (with the service). 

using this container purely as a development environment is completely okay as we laravel developers are only concerned with our application folder. however, if you want to run docker in production, the approach used within this container would be a HORRIBLE idea!
