### ISSUE TITLE
Enable mcrypt extension by default

### ISSUE THREAD

**Issue by lube8uy** [laraedit/laraedit-docker#23]
Coud you update the image with the mcrypt extension already installed?

**Comment by ibourgeois** [comment]
it is already installed and enabled by default.

see line 61 in the Dockerfile where it is installed: https://github.com/laraedit/laraedit-docker/blob/master/Dockerfile#L61
and line 82 where it is enabled: https://github.com/laraedit/laraedit-docker/blob/master/Dockerfile#L82

If you are having issues though, please copy and paste a log file or more detail so that I can help you troubleshoot it!

**Comment by lube8uy** [comment]
Thanks, I got confused with an error related to a missing key on my .env file!

**Comment by ibourgeois** [comment]
no problem
